<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('entity_translation')
->fields(array(
  'entity_type',
  'entity_id',
  'revision_id',
  'language',
  'source',
  'uid',
  'status',
  'translate',
  'created',
  'changed',
))
->values(array(
  'entity_type' => 'taxonomy_term',
  'entity_id' => '126',
  'revision_id' => '126',
  'language' => 'is',
  'source' => '',
  'uid' => '1',
  'status' => '1',
  'translate' => '0',
  'created' => '1622704056',
  'changed' => '1622704056',
))
->values(array(
  'entity_type' => 'taxonomy_term',
  'entity_id' => '126',
  'revision_id' => '126',
  'language' => 'fr',
  'source' => 'is',
  'uid' => '1',
  'status' => '1',
  'translate' => '0',
  'created' => '1622704117',
  'changed' => '1622704117',
))
->execute();
