<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('field_data_field_multifield_complex_fields', array(
  'fields' => array(
    'entity_type' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'bundle' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'deleted' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'entity_id' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'revision_id' => array(
      'type' => 'int',
      'not null' => FALSE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'language' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '32',
      'default' => '',
    ),
    'delta' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'field_multifield_complex_fields_field_tags_tid' => array(
      'type' => 'int',
      'not null' => FALSE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'field_multifield_complex_fields_field_date_value' => array(
      'type' => 'datetime',
      'not null' => FALSE,
      'mysql_type' => 'datetime',
      'pgsql_type' => 'timestamp without time zone',
      'sqlite_type' => 'varchar',
      'sqlsrv_type' => 'smalldatetime',
    ),
    'field_multifield_complex_fields_field_link_url' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '2048',
    ),
    'field_multifield_complex_fields_field_link_title' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '255',
    ),
    'field_multifield_complex_fields_field_link_attributes' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'medium',
    ),
    'field_multifield_complex_fields_id' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'entity_type',
    'entity_id',
    'deleted',
    'delta',
    'language',
  ),
  'indexes' => array(
    'entity_type' => array(
      'entity_type',
    ),
    'bundle' => array(
      'bundle',
    ),
    'deleted' => array(
      'deleted',
    ),
    'entity_id' => array(
      'entity_id',
    ),
    'revision_id' => array(
      'revision_id',
    ),
    'language' => array(
      'language',
    ),
    'field_multifield_complex_fields_field_tags_tid' => array(
      'field_multifield_complex_fields_field_tags_tid',
    ),
    'field_multifield_complex_fields_id' => array(
      'field_multifield_complex_fields_id',
    ),
  ),
  'mysql_character_set' => 'utf8',
));

$connection->insert('field_data_field_multifield_complex_fields')
->fields(array(
  'entity_type',
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'language',
  'delta',
  'field_multifield_complex_fields_field_tags_tid',
  'field_multifield_complex_fields_field_date_value',
  'field_multifield_complex_fields_field_link_url',
  'field_multifield_complex_fields_field_link_title',
  'field_multifield_complex_fields_field_link_attributes',
  'field_multifield_complex_fields_id',
))
->values(array(
  'entity_type' => 'node',
  'bundle' => 'type_with_multifields',
  'deleted' => '0',
  'entity_id' => '112',
  'revision_id' => '120',
  'language' => 'und',
  'delta' => '0',
  'field_multifield_complex_fields_field_tags_tid' => '14',
  'field_multifield_complex_fields_field_date_value' => '2021-06-03 08:15:00',
  'field_multifield_complex_fields_field_link_url' => 'https://www.drupal.org',
  'field_multifield_complex_fields_field_link_title' => 'Drupal org [rev2]',
  'field_multifield_complex_fields_field_link_attributes' => 'a:0:{}',
  'field_multifield_complex_fields_id' => '4',
))
->execute();
