<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('field_data_description_field')
->fields(array(
  'entity_type',
  'bundle',
  'deleted',
  'entity_id',
  'revision_id',
  'language',
  'delta',
  'description_field_value',
  'description_field_summary',
  'description_field_format',
))
->values(array(
  'entity_type' => 'taxonomy_term',
  'bundle' => 'vocabulary_with_multifields',
  'deleted' => '0',
  'entity_id' => '126',
  'revision_id' => '126',
  'language' => 'fr',
  'delta' => '0',
  'description_field_value' => 'Multifield term description [FR]',
  'description_field_summary' => '',
  'description_field_format' => 'filtered_html',
))
->values(array(
  'entity_type' => 'taxonomy_term',
  'bundle' => 'vocabulary_with_multifields',
  'deleted' => '0',
  'entity_id' => '126',
  'revision_id' => '126',
  'language' => 'is',
  'delta' => '0',
  'description_field_value' => 'Multifield term description [IS - default]',
  'description_field_summary' => '',
  'description_field_format' => 'filtered_html',
))
->execute();
