<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('node_revision')
->fields(array(
  'nid',
  'vid',
  'uid',
  'title',
  'log',
  'timestamp',
  'status',
  'comment',
  'promote',
  'sticky',
))
->values(array(
  'nid' => '112',
  'vid' => '119',
  'uid' => '3',
  'title' => 'Content with multifields [rev1]',
  'log' => 'Initial revision.',
  'timestamp' => '1622704732',
  'status' => '1',
  'comment' => '1',
  'promote' => '1',
  'sticky' => '0',
))
->values(array(
  'nid' => '112',
  'vid' => '120',
  'uid' => '3',
  'title' => 'Content with multifields [rev2]',
  'log' => 'New revision.',
  'timestamp' => '1622704795',
  'status' => '1',
  'comment' => '1',
  'promote' => '1',
  'sticky' => '0',
))
->execute();
