<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('taxonomy_term_data')
->fields(array(
  'tid',
  'vid',
  'name',
  'description',
  'format',
  'weight',
  'language',
  'i18n_tsid',
))
->values(array(
  'tid' => '126',
  'vid' => '109',
  'name' => 'Multifield term [IS - default]',
  'description' => 'Multifield term description [IS - default]',
  'format' => 'filtered_html',
  'weight' => '0',
  'language' => 'is',
  'i18n_tsid' => '0',
))
->execute();
