<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->insert('taxonomy_vocabulary')
->fields(array(
  'vid',
  'name',
  'machine_name',
  'description',
  'hierarchy',
  'module',
  'weight',
  'language',
  'i18n_mode',
))
->values(array(
  'vid' => '109',
  'name' => 'Vocabulary with multifields',
  'machine_name' => 'vocabulary_with_multifields',
  'description' => 'A taxonomy vocabulary for testing the migration of multifield values.',
  'hierarchy' => '0',
  'module' => 'taxonomy',
  'weight' => '0',
  'language' => 'und',
  'i18n_mode' => '2', // With up-to-date I18n, this was set to '32768'.
))
->execute();
