<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.1.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'entity_translation.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_config.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_config_instance.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_data_description_field.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_data_field_multifield_complex_fields.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_data_field_multifield_w_text_fields.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_data_name_field.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_revision_description_field.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_revision_field_multifield_complex_fields.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_revision_field_multifield_w_text_fields.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'field_revision_name_field.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'multifield.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'node.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'node_comment_statistics.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'node_counter.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'node_revision.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'node_type.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'role_permission.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'system.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'taxonomy_term_data.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'taxonomy_term_hierarchy.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'taxonomy_vocabulary.php';
include 'drupal7_multifield_on_core_fixture' . DIRECTORY_SEPARATOR . 'variable.php';
