<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('variable', array(
  'fields' => array(
    'name' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '',
    ),
    'value' => array(
      'type' => 'blob',
      'not null' => TRUE,
      'size' => 'big',
    ),
  ),
  'primary key' => array(
    'name',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('variable')
->fields(array(
  'name',
  'value',
))
->values(array(
  'name' => 'maxlength_js_article',
  'value' => 's:2:"71";',
))
->values(array(
  'name' => 'maxlength_js_label_article',
  'value' => 's:83:"Content_custom limited to @limit characters, remaining: <strong>@remaining</strong>";',
))
->values(array(
  'name' => 'maxlength_js_label_page',
  'value' => 's:76:"Content limited to @limit characters, remaining: <strong>@remaining</strong>";',
))
->values(array(
  'name' => 'maxlength_js_label_webform',
  'value' => 's:76:"Content limited to @limit characters, remaining: <strong>@remaining</strong>";',
))
->values(array(
  'name' => 'maxlength_js_page',
  'value' => 's:2:"55";',
))
->values(array(
  'name' => 'maxlength_js_webform',
  'value' => 's:2:"65";',
))
->execute();
