<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.6 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('file_managed', array(
  'fields' => array(
    'fid' => array(
      'type' => 'serial',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'uid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'filename' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'uri' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'filemime' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'filesize' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'big',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'status' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'timestamp' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'fid',
  ),
  'unique keys' => array(
    'uri' => array(
      'uri',
    ),
  ),
  'indexes' => array(
    'uid' => array(
      'uid',
    ),
    'status' => array(
      'status',
    ),
    'timestamp' => array(
      'timestamp',
    ),
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('file_managed')
->fields(array(
  'fid',
  'uid',
  'filename',
  'uri',
  'filemime',
  'filesize',
  'status',
  'timestamp',
))
->values(array(
  'fid' => '19',
  'uid' => '1',
  'filename' => 'ZQDf3IhlVPI.jpg',
  'uri' => 'public://youtube1/ZQDf3IhlVPI.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '39784',
  'status' => '1',
  'timestamp' => '1648464012',
))
->values(array(
  'fid' => '20',
  'uid' => '0',
  'filename' => 'ZQDf3IhlVPI.jpg',
  'uri' => 'public://youtube/ZQDf3IhlVPI.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '39784',
  'status' => '1',
  'timestamp' => '1648539994',
))
->values(array(
  'fid' => '21',
  'uid' => '1',
  'filename' => '4wKpHh6tolA.jpg',
  'uri' => 'public://youtube/4wKpHh6tolA.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '122950',
  'status' => '1',
  'timestamp' => '1648556645',
))
->values(array(
  'fid' => '22',
  'uid' => '1',
  'filename' => 'KcvYCSyb82Q.jpg',
  'uri' => 'public://video_embed_field_thumbnails/youtube/KcvYCSyb82Q.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '13195',
  'status' => '1',
  'timestamp' => '1648796489',
))
->values(array(
  'fid' => '23',
  'uid' => '1',
  'filename' => '632060933.',
  'uri' => 'public://video_embed_field_thumbnails/vimeo/632060933.',
  'filemime' => 'application/octet-stream',
  'filesize' => '6577',
  'status' => '1',
  'timestamp' => '1648808166',
))
->values(array(
  'fid' => '24',
  'uid' => '1',
  'filename' => 'ibqBuhVtACk.jpg',
  'uri' => 'public://video_embed_field_thumbnails/youtube/ibqBuhVtACk.jpg',
  'filemime' => 'image/jpeg',
  'filesize' => '42656',
  'status' => '1',
  'timestamp' => '1649053729',
))
->execute();
