<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_emails', array(
  'fields' => array(
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'eid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'email' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'subject' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'from_name' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'from_address' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'template' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'excluded_components' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'normal',
    ),
    'html' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'attachments' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'exclude_empty' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'extra' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'normal',
    ),
    'status' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '1',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'nid',
    'eid',
  ),
  'mysql_character_set' => 'utf8mb3',
));
