<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_component', array(
  'fields' => array(
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'cid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'pid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'form_key' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '128',
    ),
    'name' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'normal',
    ),
    'type' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '16',
    ),
    'value' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'normal',
    ),
    'extra' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'normal',
    ),
    'required' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'weight' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
    ),
  ),
  'primary key' => array(
    'nid',
    'cid',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_component')
->fields(array(
  'nid',
  'cid',
  'pid',
  'form_key',
  'name',
  'type',
  'value',
  'extra',
  'required',
  'weight',
))
->values(array(
  'nid' => '2',
  'cid' => '1',
  'pid' => '0',
  'form_key' => 'some_component',
  'name' => 'some component',
  'type' => 'textfield',
  'value' => '123',
  'extra' => 'a:8:{s:11:"description";s:9:"some text";s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";s:9:"maxlength";s:2:"12";s:9:"minlength";s:1:"4";}',
  'required' => '1',
  'weight' => '0',
))
->values(array(
  'nid' => '2',
  'cid' => '2',
  'pid' => '0',
  'form_key' => 'test',
  'name' => 'test',
  'type' => 'email',
  'value' => '',
  'extra' => 'a:5:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";}',
  'required' => '0',
  'weight' => '1',
))
->values(array(
  'nid' => '2',
  'cid' => '4',
  'pid' => '0',
  'form_key' => 'test1234',
  'name' => 'test1234',
  'type' => 'textfield',
  'value' => '',
  'extra' => 'a:5:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";}',
  'required' => '0',
  'weight' => '3',
))
->values(array(
  'nid' => '2',
  'cid' => '5',
  'pid' => '0',
  'form_key' => 'date11',
  'name' => 'date11',
  'type' => 'date',
  'value' => '',
  'extra' => 'a:4:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";}',
  'required' => '0',
  'weight' => '4',
))
->values(array(
  'nid' => '2',
  'cid' => '6',
  'pid' => '0',
  'form_key' => 'date12',
  'name' => 'date12',
  'type' => 'date',
  'value' => '',
  'extra' => 'a:4:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";}',
  'required' => '0',
  'weight' => '5',
))
->values(array(
  'nid' => '2',
  'cid' => '7',
  'pid' => '0',
  'form_key' => 'test123456',
  'name' => 'test123456',
  'type' => 'email',
  'value' => '',
  'extra' => 'a:5:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";}',
  'required' => '0',
  'weight' => '6',
))
->values(array(
  'nid' => '3',
  'cid' => '1',
  'pid' => '0',
  'form_key' => 'an1',
  'name' => 'an1',
  'type' => 'textfield',
  'value' => '',
  'extra' => 'a:5:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";}',
  'required' => '0',
  'weight' => '0',
))
->values(array(
  'nid' => '3',
  'cid' => '2',
  'pid' => '0',
  'form_key' => 'an2',
  'name' => 'an2',
  'type' => 'textfield',
  'value' => '',
  'extra' => 'a:5:{s:13:"title_display";s:6:"before";s:17:"description_above";i:0;s:7:"private";i:0;s:15:"wrapper_classes";s:0:"";s:11:"css_classes";s:0:"";}',
  'required' => '0',
  'weight' => '1',
))
->execute();
