<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_submissions', array(
  'fields' => array(
    'sid' => array(
      'type' => 'serial',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'serial' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'uid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'is_draft' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
    ),
    'highest_valid_page' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
    ),
    'submitted' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ),
    'completed' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ),
    'modified' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ),
    'remote_addr' => array(
      'type' => 'varchar',
      'not null' => FALSE,
      'length' => '128',
    ),
  ),
  'primary key' => array(
    'sid',
  ),
  'unique keys' => array(
    'sid_nid' => array(
      'sid',
      'nid',
    ),
    'nid_serial' => array(
      'nid',
      'serial',
    ),
  ),
  'indexes' => array(
    'nid_uid_sid' => array(
      'nid',
      'uid',
      'sid',
    ),
    'nid_sid' => array(
      'nid',
      'sid',
    ),
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_submissions')
->fields(array(
  'sid',
  'nid',
  'serial',
  'uid',
  'is_draft',
  'highest_valid_page',
  'submitted',
  'completed',
  'modified',
  'remote_addr',
))
->values(array(
  'sid' => '1',
  'nid' => '2',
  'serial' => '1',
  'uid' => '1',
  'is_draft' => '0',
  'highest_valid_page' => '0',
  'submitted' => '1642491538',
  'completed' => '1642491538',
  'modified' => '1642491538',
  'remote_addr' => '127.0.0.1',
))
->execute();
