<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_validation_rule', array(
  'fields' => array(
    'ruleid' => array(
      'type' => 'serial',
      'not null' => TRUE,
      'size' => 'normal',
      'unsigned' => TRUE,
    ),
    'rulename' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'validator' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '255',
      'default' => '',
    ),
    'data' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'error_message' => array(
      'type' => 'text',
      'not null' => FALSE,
      'size' => 'normal',
    ),
    'negate' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'tiny',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'weight' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
    ),
  ),
  'primary key' => array(
    'ruleid',
  ),
  'indexes' => array(
    'nid' => array(
      'nid',
    ),
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_validation_rule')
->fields(array(
  'ruleid',
  'rulename',
  'nid',
  'validator',
  'data',
  'error_message',
  'negate',
  'weight',
))
->values(array(
  'ruleid' => '1',
  'rulename' => 'some rule',
  'nid' => '2',
  'validator' => 'numeric',
  'data' => '100',
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '2',
  'rulename' => 'equal_values',
  'nid' => '2',
  'validator' => 'equal',
  'data' => NULL,
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '3',
  'rulename' => 'some several',
  'nid' => '2',
  'validator' => 'someofseveral',
  'data' => '=2',
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '4',
  'rulename' => 'comp',
  'nid' => '2',
  'validator' => 'comparison',
  'data' => '>',
  'error_message' => 'error',
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '5',
  'rulename' => 'equal_2',
  'nid' => '2',
  'validator' => 'equal',
  'data' => NULL,
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '6',
  'rulename' => 'some22',
  'nid' => '2',
  'validator' => 'someofseveral',
  'data' => '=3',
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '7',
  'rulename' => 'an_rule_1',
  'nid' => '3',
  'validator' => 'numeric',
  'data' => '100',
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->values(array(
  'ruleid' => '8',
  'rulename' => 'eq_anaother',
  'nid' => '3',
  'validator' => 'equal',
  'data' => NULL,
  'error_message' => NULL,
  'negate' => '0',
  'weight' => '0',
))
->execute();
