<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_roles', array(
  'fields' => array(
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'rid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'nid',
    'rid',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_roles')
->fields(array(
  'nid',
  'rid',
))
->values(array(
  'nid' => '2',
  'rid' => '1',
))
->values(array(
  'nid' => '2',
  'rid' => '2',
))
->values(array(
  'nid' => '3',
  'rid' => '1',
))
->values(array(
  'nid' => '3',
  'rid' => '2',
))
->execute();
