<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_submitted_data', array(
  'fields' => array(
    'nid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'sid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'cid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'small',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'no' => array(
      'type' => 'varchar',
      'not null' => TRUE,
      'length' => '128',
      'default' => '0',
    ),
    'data' => array(
      'type' => 'text',
      'not null' => TRUE,
      'size' => 'medium',
    ),
  ),
  'primary key' => array(
    'nid',
    'sid',
    'cid',
    'no',
  ),
  'indexes' => array(
    'nid' => array(
      'nid',
    ),
    'sid_nid' => array(
      'sid',
      'nid',
    ),
    'data' => array(
      array(
        'data',
        '64',
      ),
    ),
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_submitted_data')
->fields(array(
  'nid',
  'sid',
  'cid',
  'no',
  'data',
))
->values(array(
  'nid' => '2',
  'sid' => '1',
  'cid' => '1',
  'no' => '0',
  'data' => '1212',
))
->execute();
