<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

$connection->schema()->createTable('webform_validation_rule_components', array(
  'fields' => array(
    'ruleid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
    'cid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'size' => 'normal',
      'default' => '0',
      'unsigned' => TRUE,
    ),
  ),
  'primary key' => array(
    'ruleid',
    'cid',
  ),
  'mysql_character_set' => 'utf8mb3',
));

$connection->insert('webform_validation_rule_components')
->fields(array(
  'ruleid',
  'cid',
))
->values(array(
  'ruleid' => '1',
  'cid' => '1',
))
->values(array(
  'ruleid' => '1',
  'cid' => '4',
))
->values(array(
  'ruleid' => '2',
  'cid' => '1',
))
->values(array(
  'ruleid' => '2',
  'cid' => '4',
))
->values(array(
  'ruleid' => '3',
  'cid' => '4',
))
->values(array(
  'ruleid' => '3',
  'cid' => '5',
))
->values(array(
  'ruleid' => '3',
  'cid' => '6',
))
->values(array(
  'ruleid' => '4',
  'cid' => '4',
))
->values(array(
  'ruleid' => '4',
  'cid' => '5',
))
->values(array(
  'ruleid' => '5',
  'cid' => '4',
))
->values(array(
  'ruleid' => '5',
  'cid' => '5',
))
->values(array(
  'ruleid' => '5',
  'cid' => '6',
))
->values(array(
  'ruleid' => '6',
  'cid' => '4',
))
->values(array(
  'ruleid' => '6',
  'cid' => '5',
))
->values(array(
  'ruleid' => '7',
  'cid' => '1',
))
->values(array(
  'ruleid' => '7',
  'cid' => '2',
))
->values(array(
  'ruleid' => '8',
  'cid' => '1',
))
->values(array(
  'ruleid' => '8',
  'cid' => '2',
))
->execute();
