<?php
// phpcs:ignoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 9.2.9 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

include 'drupal7' . DIRECTORY_SEPARATOR . 'field_config.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'field_config_instance.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'file_managed.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'file_usage.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'node.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'node_access.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'node_revision.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'node_type.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'role.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'role_permission.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'system.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'users.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'users_roles.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_component.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_conditional.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_conditional_actions.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_conditional_rules.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_emails.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_last_download.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_roles.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_submissions.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_submitted_data.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_validation_rule.php';
include 'drupal7' . DIRECTORY_SEPARATOR . 'webform_validation_rule_components.php';
